### ISSUE TITLE
rake aborted! på rake db:setup

### ISSUE THREAD

**Issue by ch222kv** [HenrikGabrielsson/1DV450_hg222aa#7]
```
rake aborted!
TZInfo::DataSourceNotFound: No source of timezone data could be found.
Please refer to http://tzinfo.github.io/datasourcenotfound for help resolving th
is error.
c:/Users/Chrille/School/1DV450/Peer Review/HenrikGabrielsson/1DV450_hg222aa-1.0.
0/1DV450_hg222aa-1.0.0/apiKeyHandler/config/environment.rb:5:in `<top (required)
>'
TZInfo::ZoneinfoDirectoryNotFound: None of the paths included in TZInfo::Zoneinf
oDataSource.search_path are valid zoneinfo directories.
c:/Users/Chrille/School/1DV450/Peer Review/HenrikGabrielsson/1DV450_hg222aa-1.0.
0/1DV450_hg222aa-1.0.0/apiKeyHandler/config/environment.rb:5:in `<top (required)
>'
Tasks: TOP => db:setup => db:schema:load_if_ruby => environment
(See full trace by running task with --trace)
```

Förslagsvis så lägger du till en `gem 'tzinfo-data'` del i din Gemfile så slipper du såna problem.

**Comment by HenrikGabrielsson** [comment]
Har inte fått detta felet själv, så visste inte om det, men förhoppningsvis hjälpte gem:et som du tipsade om!
